apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: my-app-container
    image: busybox:latest
    command: ["/bin/sh", "-c", "echo 'My environment variables:'; printenv | grep DB_"]
    env:
      - name: DATABASE_USER_ENV
        valueFrom:
          secretKeyRef:
            name: db-credentials-secret
            key: DB_USER
      - name: DATABASE_PASSWORD_ENV
        valueFrom:
          secretKeyRef:
            name: db-credentials-secret
            key: DB_PASSWORD
  restartPolicy: Never